spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/rockpaperscissorsdb
    username: newuser
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/META-INF/resources/webjars/
