name: Diagnose APT Environment

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Check All Package Availability
        run: |
          sudo apt-get update
          for package in libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb; do
            echo "Checking package: $package"
            apt-cache policy $package || echo "$package not found in repositories"
            sudo apt-get install --dry-run $package || echo "Failed to install: $package"
          done