services:
  postgres:
    image: postgres:16.2-alpine
    container_name: postgres-cont
    restart: always
    environment:
      POSTGRES_DB: rockpaperscissorsdb
      POSTGRES_USER: newuser
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - rockpaperscissorsdb:/var/lib/postgresql/data

  app:
    build:
      context: ../..
      dockerfile: ops/docker/Dockerfile
    image: rockpaperscissors:1.0
    container_name: rockpaperscissors_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rockpaperscissorsdb
      SPRING_DATASOURCE_USERNAME: newuser
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

volumes:
  rockpaperscissorsdb: